language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"

install:
  - pip install -U coverage codecov
  - pip install -U flake8
  - pip install -U $DJANGO
  - pip freeze

script:
  - flake8 simple_history
  - coverage run setup.py test

matrix:
  exclude:
    - python: 2.7
      env: DJANGO="Django>=2.0,<2.1"
      env: DJANGO="Django>=2.1,<2.2"
    - python: 3.4
      env: DJANGO="Django>=2.1,<2.2"

after_success: codecov
